# Generated by Django 3.2 on 2021-04-21 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 0, 59, 35, 753829)),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Humanities & Social Sciences', 'Humanities & Social Sciences'), ('Science & Technology', 'Science & Technology'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('Graphic Novel', 'Graphic Novel'), ('Short Story & Essays', 'Short Story & Essays'), ('Poem', 'Poem'), ('Memoir & Autobiography', 'Memoir & Autobiography'), ('Food & Drink', 'Food & Drink'), ('Art & Photography', 'Art & Photography'), ('Self-help & Personal Growth', 'Self-help & Personal Growth'), ('Mythology', 'Mythology'), ('Travel', 'Travel')], default='Fiction', max_length=50),
        ),
    ]
