# Generated by Django 3.2 on 2021-04-21 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='period',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 2, 33, 50, 816951)),
        ),
    ]
