# Generated by Django 3.2 on 2021-04-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
