# Generated by Django 3.2 on 2021-04-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210418_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avalability',
            new_name='available',
        ),
    ]
