# Generated by Django 3.2 on 2021-04-22 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 13, 47, 31, 718201)),
        ),
    ]
