# Generated by Django 3.2 on 2021-04-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
