# Generated by Django 3.2 on 2021-04-25 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 23, 16, 25, 523151)),
        ),
    ]
